[package]
name = "minepatch"
version = "0.1.0"
edition = "2021"
authors = ["Tim Anhalt (BitTim)"]
description = "A utility to easily create, manage and apply patches for Minecraft modpacks"
readme = "README.md"
repository = "https://github.com/BitTim/Minepatch"
license = "GPL-3"

[env]
CARGO_PKG_QUALIFIER = "dev"
CARGO_PKG_ORGANIZATION = "BitTim"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
directories = "5.0.1"
csv = "1.3.1"